import "./assets/css/global.css";
import type { Metadata } from "next";
import { Header } from "./components/header";
import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-inter text-sm font-normal text-gray-500">
        <Header />
        <main>{children}</main>
        <footer>
          <div className="logo"></div>
        </footer>
      </body>
    </html>
  );
}
